microsoft/OCR-Form-Tools

src/services/projectService.ts

We will load project before adding tag now, so it will clear the added tag.

fix: don't load label/fields when load project

---

src/react/components/pages/predict/predictPage.tsx

display detailed error message when fetch fails

fix: display detailed error message when fetch

---

src/App.scss

This is a test: first commit to repo + small bugfix on #192

fix: on overflowing .app-content div when on create

---

src/react/components/common/tagInput/tagInput.tsx

The only condition needed is: "selected region equals tag category or tag is free" right?
`!this.isSelectionMark(selectedRegions[0].category) && !this.isSelectionMark(tag.type)`
will become a problem

Stew ro/check tag type and region catagory compatibility

---

src/react/components/pages/connections/connectionForm.tsx
src/react/components/pages/editorPage/canvas.tsx

applyTag is calling updateRegions which calls **async** onAssetMetadataChanged. So when we call setTags, it is passed the project.tags before the tags have updated
Ideally we would pass the updated tags to setTags. This is a workaround

fix: set document count to 1 when inffering tag type

---

src/react/components/pages/editorPage/editorPage.scss

fix on: Split pane overlapping with asset preview scrollbar #250

fix: overlapping left split pane

---

src/react/components/pages/editorPage/tableView.scss
src/react/components/pages/editorPage/tableView.tsx

I adapted table style to be more align with overall app design:
-add horizontal padding for cells content
- make borders less prominent - darker and bit bolder (for readability )
- moved to the left and spaced out scrollbar (it's not touching  table anymore)
- add some space to close button from the edges (too close in my opinion)
...and fix some redundant  code and misspelling
After:
Before:

Style for the table view

---

src/react/components/pages/modelCompose/composeModelView.tsx
src/react/components/pages/modelCompose/modelCompose.scss

Fix overflow on warning when there's a lot of excluded models + some style changes

fix: overflow of excluded models list

---

src/react/components/pages/modelCompose/composeModelView.tsx
src/react/components/pages/modelCompose/modelCompose.scss

feat: add modelCompose icon and created time

---

src/common/localization/en-us.ts
src/common/localization/es-cl.ts
src/common/strings.ts
src/react/components/pages/editorPage/editorPage.tsx
src/services/ocrService.ts
src/services/projectService.ts

When user lose access to storage when they already have opened project we need to show appropriate message. Now, the tool gives misleading error message of "Bad Image URL".
Also in case of lost access we need handle exceptions.
on issue #440

fix: resolve unhandled exceptions and new error message for OCR service

---

src/react/components/pages/editorPage/canvas.scss

***Before:*** 
on hover:
***After change:***
on hover:

fix buttons styles - makes them more visible

---

src/electron/main.ts

Now for zoomIn we use `Cmd` + `=`
fixes #580

fix: zoomIn keyboard shortcut for macOS

---

src/redux/reducers/recentProjectsReducer.ts

Tt is necessary to refresh currentProjects when open a project.
The project pages (predictPage.tsx, editorPage.tsx, modelCompose.tsx, projectSettings.tsx, trainPage.tsx)  get the project from recentProjects, if the project is changed on blobStorage, but not refresh the currentProjects data, the data may conflicted,

refresh currentProjects when load project

---

src/common/localization/en-us.ts
src/common/localization/es-cl.ts
src/common/strings.ts
src/services/assetService.ts

* add try-catch for fetch()
* use poll function instead try-catch
* style: naming
* fix: poll and resolve for fetched failed
* add try-catch for fetch()
* use poll function instead try-catch
* style: naming
* merge + misc
* deletes unused import
* fix: check for failed fetch promise
* since it's not blocking error - console.err(message) instead 'toast'
* switch to console.err for spooded mime type too
Co-authored-by: stew-ro <v-stewro@microsoft.com>

cherry-pick 530545c -- fix: "failed to fetch()" error (#491)

---

src/react/components/common/imageMap/imageMap.tsx
src/react/components/common/tagInput/tagInput.scss
src/react/components/common/tagInput/tagInput.tsx
src/react/components/common/tagInput/tagInputItem.tsx
src/react/components/pages/editorPage/canvas.tsx
src/react/components/pages/editorPage/editorPage.tsx
src/redux/reducers/recentProjectsReducer.ts

With "highlight current tag", user can quickly locating to the related tag in the TagInput component.
1. select a region in canvas in EditPage
2. double click on the region
the TagInput will scroll to the tag realated to the field you clicked.
double click tag go to label page 
1. double click on a tag whitch realted label not in current page.
the page will switch to the correct page

new feature: highlight current tag

---

src/react/components/pages/editorPage/canvas.tsx

fix issue of "When an auto-labeled tag is revised by re-assigning it's value, the tag does not show as revised"

fix issue of 733

---

src/react/components/pages/editorPage/canvas.tsx
src/react/components/pages/editorPage/editorPage.tsx

1. Async OCR and AutoLabelling state while running multiple documents
2. Add necessary tags and labels after running autolabelling

sync ocr and autolabeling state, include necessary tags and lables after running autolabelling

---

src/react/components/pages/editorPage/canvas.tsx

on #781 
When user double click on tag which has no value - the app will through the error.
Fix will handle this error.

fix: handle type error on double click on tag

---

src/react/components/pages/editorPage/canvas.tsx
src/services/assetService.ts
src/services/projectService.ts

Root cause: when first time tagging, labelData is null such that labelData.$schema is causing app crash.
Resolve: handle cases when labelData is null.

Fix first time labeling field will crash.

---

src/react/components/pages/editorPage/canvas.tsx
src/react/components/pages/editorPage/editorPage.tsx

**Scenario.** The table content is read from `regions` which is not set when `selectedAsset` is changed.
**Solution.** Set regions from `labelData` when `selectedAsset` is changed with the loaded metadata.

Initial load/display labeled table content didn't happen

---

src/react/components/pages/editorPage/editorPage.tsx

Check if `selectedRegions` exists in `handleTableCellClick`.

Get error when assigning table tag without selected region(s)

---

src/common/constants.ts

* Hide predict mode toggle in prod env.
* Change default api version to v2.1-preview.3
Co-authored-by: Simo Hsieh (ManpowerGroup Taiwan) <a-simohsieh@microsoft.com>

Change default API version to v2.1-preview3. (#872)

---

src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx

Change following API compose scenarios, includes
1.  While a user click "Run analysis" button,  the compose API text area -> the composed API will be
- "/formrecognizer/v2.1-preview.3/prebuilt/invoice/analyze?" -> "/formrecognizer/v2.1-preview.3/prebuilt/invoice/analyze?"
- "/formrecognizer/v2.1-preview.3/pre" -> "/formrecognizer/v2.1-preview.3/prebuilt/invoice/analyze?"
2. While a user changes the "form type" field or the "locale" field or the "page range" field. We will recompose the query by settings and show it on the compose API text area.

Fix compose api error.

---

src/models/applicationState.ts
src/react/components/pages/editorPage/canvas.tsx
src/react/components/pages/editorPage/tableView.tsx
src/services/ocrService.ts

- Modify `canvas` code to handle `analyzeResult` in v3.0 schema.
- Add `"v3.0-preview.1"` to `APIVersionPatches`.
- Modify `tableView` to handle table cells in v3.0 schema.
- Modify `ocrService` to adjust request for fetching v3.0 OCR result.

Handle v3.0 schema on CustomForm scenario

---

src/common/constants.ts
src/react/components/common/predictionFilePicker/predictionFilePicker.tsx
src/react/components/pages/prebuiltPredict/layoutHelper.ts
src/react/components/pages/prebuiltPredict/layoutPredictPage.tsx
src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
src/react/components/pages/prebuiltPredict/tableHelper.ts
src/react/components/pages/predict/predictResult.tsx
src/services/ocrService.ts

- Add `apiVersionQuery` for 3.0 API to `constants`.
- Replace handling logic in `tableHelper`, `layoutHelper`, `predictResult` with v3.0 schema.
- Use first `boundingRegion` to extract `pageNumber` and `boundingBox` for a field.
- Adjust file validation logic in `predictionFilePicker`.
- Replace endpoints in `layoutPredictPage` and `prebuiltPredictPage`

Handle v3.0 schema on Layout/Prebuilt scenario 

---

src/react/components/pages/prebuiltPredict/tableHelper.ts

Find table index from full `tables` list by comparing their `boundingRegions`, since this index will be saved in `tableIDToIndexMap` and referenced by `getTable`.

Fix table indexing bug

---

src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx

Replace v2.1 endpoint URL with v3.0 one in the constructor of `prebuiltPredictPage`.

Fix initial endpoint URL on Prebuilt Page

---

src/react/components/pages/train/trainPage.tsx

[FOTT] Remove "/" in model training request when documents are in root folder.
After verification, only version 3.0 has this problem
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10644514/null

[FOTT] Remove "/" in model training request when documents are in root folder.

---

src/react/components/pages/modelCompose/modelCompose.tsx

fix: hide the prebuilt models in the model compose page.
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10622828/

hide the prebuilt models in the model compose page.

---

scripts/redact_cli_py/CHANGELOG.md
scripts/redact_cli_py/README.md
scripts/redact_cli_py/redact/utils/redact_policy.py
scripts/redact_cli_py/tests/utils/test_redact_policy.py

Support to redact some Latin ligature letters and letters with diacritics
We currently cannot handle accented letter like é and ligature letter like œ, which is common in French. Need to support this. We also expand the language coverage out of just French. Please check the code for the actual charset we have taken care of.
Before merging this PR, please make sure below works are done and marked items with 'x'.

Redaction Toolkit | Support to redact some Latin ligature letters and letters with diacritics

---

src/react/components/pages/homepage/homePage.scss
src/react/components/pages/homepage/homePage.tsx
yarn.lock

Add banner for FoTT deprecation on Oct 2024.
- All the documentation link to v3.1 version.
- All the tool alternatives link to v2.0 branch/release.
Add UI screenshot:

Add deprecation banner for FoTT v2.0
