microsoft/OCR-Form-Tools

- README.md
link is https://youtu.be/GRGs18lZJ1E?t=462
> add a demo link

- src/services/projectService.ts
check for previous project tags exists before updating current project tags
> refactor: check prev tags exist before tag color update

- src/react/components/common/tagInput/tagInput.scss
- src/react/components/common/tagInput/tagInput.test.tsx
- src/react/components/common/tagInput/tagInput.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/projectSettings/projectSettingsPage.tsx
- src/react/components/pages/train/trainPage.tsx
- src/redux/actions/projectActions.ts
- src/services/projectService.ts
> fix: correct the tag sync logic

- README.md
provide clear instruction about getting sample files and about root and sub-folders.
> update readme about sample files

- .env
- package-lock.json
- package.json
- src/common/utils.ts
- src/models/applicationState.ts
- src/react/components/common/alert/alert.tsx
- src/react/components/common/arrayField/arrayFieldTemplate.tsx
- src/react/components/common/assetPreview/pdfAsset.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasCommandBar.tsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/train/trainPage.tsx
- src/react/components/shell/skipButton.tsx
- src/services/projectService.ts
Since we're planning to rename "checkbox" feature to "Selection Mark" - renamed appropiate references.
> refactor: renaming checkbox->selectionMark

- src/react/components/shell/statusBar.scss
- src/react/components/shell/statusBar.tsx
Statusbar version number now points to CHANGELOG.md as per issue #186
> feature: link in status bar to changelog

- src/react/components/pages/editorPage/editorPage.scss
- src/react/components/pages/editorPage/editorPage.tsx
> fix: adjustable left splitpane width on issue #237

- src/react/components/shell/keyboardShortcuts.tsx
> fix: unique key value for all list elements + refactor

- README.md
about using Azure Storage Explorer, and SAS URL.
> update to make instruction clear

- src/react/components/shell/keyboardShortcuts.scss
> fix: correct positioning of close icon + increased icon size

- src/App.tsx
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/shell/keyboardShortcuts.tsx
> feature: shortcuts icon toolbar

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/editorPage/canvasCommandBar.tsx
> feature: localization for canvas commandbar items #319

- src/react/components/common/tagInput/tagInput.scss
- src/react/components/common/tagInput/tagInput.tsx
- src/react/components/pages/editorPage/canvasCommandBar.tsx
- src/services/projectService.ts
Disable selection mark for GA version on issue #336
> disable selectionMark feature

- src/react/components/pages/modelCompose/modelCompose.tsx
> fix: style fix for list items of column "Created" in composedModel

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/react/components/pages/modelCompose/composeModelView.tsx
> fix: grammar and capitalization

- src/react/components/pages/modelCompose/composeModelView.tsx
> fix: disable interactions when modal is open

- src/common/constants.ts
- src/react/components/pages/modelCompose/composeModelView.tsx
- src/react/components/pages/modelCompose/modelCompose.scss
- src/react/components/pages/modelCompose/modelCompose.tsx
> fix: wait until composed model is ready

- src/react/components/pages/train/trainPage.scss
- src/react/components/pages/train/trainPage.tsx
> fix: styling

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/modelCompose/composeCommandBar.tsx
- src/react/components/pages/modelCompose/modelCompose.tsx
> fix: modelCompose accessibility issues

- src/react/components/pages/modelCompose/composeModelView.tsx
- src/react/components/pages/modelCompose/modelCompose.scss
> fix: multiple scrollbars and styling on modal when lots of models (modelCompose)

- CONTRIBUTING.md
- README.md
- package.json
- public/index.html
- public/manifest.json
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
> docs: rename to FoTT

- CONTRIBUTING.md
- README.md
- package.json
- public/index.html
- public/manifest.json
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
changes from 2abb0cb062c34697ff6fd874bef755b5c01c97f0
> docs: rename to FoTT (#387)

- src/react/components/pages/predict/predictModelInfo.scss
- src/react/components/pages/predict/predictModelInfo.tsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/predict/predictResult.tsx
> feat: enable new model info in preditct page

- src/react/components/pages/train/trainRecord.tsx
> Alex krasn/fix model info enclosing element error on #407

- .env
- README.md
- README.zh-cn.md
- docs/DEBUG.md
- docs/REACTAPP.md
> docs: npm -> yarn

- src/services/assetService.ts
> fix: on assetFormat undefined

- src/services/assetService.ts
* fix: on assetFormat undefined
* fix for multiple toasts
* refactor
* fix for tiff/tif files
* style: fix empty line
> fix: on assetFormat undefined (#413)

- src/react/components/common/assetPreview/pdfAsset.tsx
* fix: handle worker deleted error
* style: fix not strict comparison
> fix: handle worker deleted error (#381)

- src/react/components/pages/train/trainPage.tsx
> fix: reset modelName input field value  after train

- src/react/components/pages/predict/predictPage.tsx
> fix: DOM table nesting

- package.json
- src/App.tsx
- src/common/constants.ts
- src/providers/telemetry/telemetryProvider.jsx
- src/react/components/pages/modelCompose/composeModelView.tsx
- src/react/components/pages/modelCompose/modelCompose.tsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/train/trainPage.tsx
- src/services/telemetryService.ts
- yarn.lock
you need to put your ```AppInsightsInstrumentationKey``` in telemetryProvide.jsx
> feat: enable internal telemetry

- src/react/components/pages/editorPage/editorPage.scss
> fix: magrin for filenames

- src/react/components/pages/modelCompose/modelCompose.tsx
> feat: show only ready models in the list

- src/react/components/pages/modelCompose/modelCompose.tsx
- src/services/telemetryService.ts
> telemetry/feat: override page view names - now  english only

- package.json
- src/App.tsx
- src/common/constants.ts
- src/providers/telemetry/telemetryProvider.jsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/train/trainPage.tsx
- src/services/telemetryService.ts
- yarn.lock
* add packages
* initial setup
* tracking only events and page views
* add key and check if key is present and insights instantiated
> feat: enable internal telemetry (#431)

- README.md
* docs: added telemetry disclaimer
* fix: grammar
> docs: add telemetry disclaimer to readme (#449)

- src/react/components/pages/train/trainPage.tsx
- src/services/telemetryService.ts
* feat: add apiVersion
* fix: key
* refactor: move insights apiVersion into telemetryServise.ts
> feat: add apiVersion to telemetry (#448)

- src/services/telemetryService.ts
* telemetry/feat: override page view names - now  engllish only
* add all page names
> telemetry/feat: override page view names - now  english only (#472)

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/react/components/common/tagInput/tagInput.tsx
> more detailed message about reassigned different tag types and increased delay for auto-close (now 7 sec)

- README.md
> docs: update telemetry disclaimer

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/modelCompose/composeModelView.tsx
- src/react/components/pages/modelCompose/modelCompose.tsx
> fix: show loading indicator while loading model info

- docs/manual_testing/manual-test-runbook.md
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/train/trainPage.tsx
> feature: enable download JSON of trained model

- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/common/strings.ts
- src/react/components/pages/train/trainPage.tsx
fix issue #570
Error message after change:
> fix: "Azure blob storage"  error on on premise scenario

- src/react/components/common/tagInput/tableTagLabeling.scss
- src/react/components/common/tagInput/tableTagLabeling.tsx
> feat: table view styles

- src/react/components/common/tagInput/tableTagConfig.scss
- src/react/components/common/tagInput/tableTagConfig.tsx
> feat: table preview

- src/electron/providers/storage/localFileSystem.ts
> update asset labelingState when load local project

- src/common/constants.ts
- src/react/components/pages/modelCompose/modelCompose.tsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/train/trainPage.tsx
- src/services/predictService.ts
* refactor: change drawn region icon
* fix: use api version selected in project settings
* fix: change interpolate value for api version
> Stew ro/use api version selected in project settings (#678)

- src/services/assetService.ts
fix the issue of deleting tag.
> fix issue of deleting tag

- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
> show business card result

- src/common/mockFactory.ts
- src/react/components/common/tagInput/tagInput.tsx
- src/react/components/common/tagInput/tagInputItem.tsx
- src/react/components/common/tagInput/tagInputItemLabel.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/react/components/pages/train/trainPage.tsx
- src/redux/actions/projectActions.ts
- src/services/assetService.ts
> remain label data while deleting all labels

- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/train/trainPage.tsx
- src/services/assetService.ts
fix issue of incorrect asset state after training.
> handle training state logical

- src/react/components/pages/editorPage/canvas.tsx
the labeldata could be null. So, need to check null.
> check whether the label data is null

- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/editorPage.tsx
- src/services/ocrService.ts
> remain unvisited asset state if there isn't ocr data

- src/services/assetService.ts
deep clone asset data to deal with redux state mutation issue.
> deep clone asset to deal with redux state mutation issue

- src/react/components/pages/editorPage/editorPage.tsx
Prevent leaving while running auto labelling on multiple documents
> prevent leaving while running auto labelling on mutiple documents

- src/react/components/pages/train/trainPage.tsx
add logical to skip saving unchanged asset while training
> skip saving unchanged asset while training

- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
> show all detected fields in prebuilt predict result

- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.scss
- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
* add local in prebuiltPredictPage
* change locales to Local
(cherry picked from commit 7a93c41417468ad748a3a512972ed7f1daccbd1a)
> preview2 add locale in prebuilt predict page

- src/react/components/pages/train/trainPage.scss
- src/react/components/pages/train/trainPage.tsx
- src/react/components/pages/train/trainTable.tsx
> fix: support long tag names in train result

- azure-pipelines-pr.yml
Add a new CI script for PR validation as I tried to create a new PR pipeline on Azure DevOps. Will need to delete the old one afterwards.
> Set up new CI with Azure Pipelines

- LICENSE
- package.json
> update appVersion to 2.1.2

- package.json
Update master branch version to 2.1.3
> Update master branch version to 2.1.3

- CHANGELOG.md
Update changelog for reflecting recent updates.
> Update changelog for reflecting recent updates.

- package.json
- src/common/utils.ts
- src/react/components/common/common.scss
- src/react/components/pages/prebuiltPredict/layoutPredictPage.tsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/predict/predictResult.tsx
- yarn.lock
> download csv file

- src/react/components/common/pageRange/pageRange.tsx
- src/react/components/common/prebuiltSetting/prebuiltSetting.tsx
- src/react/components/pages/connections/connectionForm.tsx
- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
* Add configurable URL to prebuilt page
* Fix page range RegEx to accept comma
> Make url configurable, fix page range RegEx

- src/react/components/pages/modelCompose/modelCompose.tsx
Add condition handling when sorted column is not assigned.
>  Get error when clicking on "Load next page" in model compose page

- src/common/constants.ts
- src/common/localization/en-us.ts
- src/react/components/common/tagInput/tableTagConfig.tsx
- src/react/components/common/tagInput/tableTagLabeling.tsx
- src/react/components/common/tagInput/tagInput.tsx
- src/react/components/common/tagInput/tagInputItem.tsx
- src/react/components/common/tagInput/tagInputItemLabel.tsx
- src/react/components/pages/editorPage/canvas.tsx
- src/react/components/pages/editorPage/canvasCommandBar.tsx
- src/react/components/pages/prebuiltPredict/layoutPredictPage.tsx
- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
- src/react/components/pages/predict/predictPage.tsx
- src/react/components/pages/predict/predictResult.tsx
- src/react/components/pages/projectSettings/projectForm.tsx
- src/redux/actions/projectActions.ts
- src/services/assetService.ts
- src/services/projectService.ts
> Fix warnings on console

- README.ja-jp.md
- README.md
Adding Japanese README: README.ja-jp.md
> Adding Japanese README

- src/react/components/common/tagInput/tagInput.tsx
> Fix click array from a table tag but nothing happen.

- src/react/components/pages/prebuiltPredict/LoadFileHelper.ts
> Fix button remains disabled even if with supported file type.

- src/common/utils.ts
- src/react/components/pages/homepage/homePage.tsx
- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
- src/redux/reducers/currentProjectReducer.ts
- src/services/projectService.ts
Tested scenarios
- Open a new project with blob storage not contain a .fott file.
- Open an old project by opening a cloud project with blob storage not contain a .fott file.
- Open an old project by opening a new project with blob storage not contain a .fott file.
> Fix tag color error with backward compatibility.

- src/electron/providers/storage/localFileSystem.ts
- src/providers/storage/azureBlobStorage.ts
- src/services/projectService.ts
- Parallel GET label.json files.
- Atomic update tagCount.
> Change sequential requests for getting label.json files to parallel.

- docs/manual_testing/manual-test-runbook.md
- package.json
- src/common/constants.ts
- src/common/localization/en-us.ts
- src/common/localization/es-cl.ts
- src/react/components/common/apiVersionPicker/apiVersionPicker.tsx
- src/react/components/pages/prebuiltPredict/prebuiltPredictPage.tsx
1. Upgrade app version to 2.1
2. Set API version default to 2.1
> Upgrade app version and api version.

- src/react/components/pages/train/trainPage.tsx
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10719208
> increase training timeout to 90mins

- src/react/components/pages/train/trainPage.tsx
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10719208
> increase training timeout to 90mins- 3.1

- src/react/components/pages/editorPage/canvas.tsx
fixBug:An error occurs when adding a layer to a tag
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10482819/
> fix:An error occurs when adding a layer to a tag

- src/providers/storage/azureBlobStorage.ts
Currently FOTT submits Analyze Layout requests to the service as:
```json
{ "url": "https://account.blob.core.windows.net/container/folder%2Ffile.pdf" }
```
This is due to JS Azure Storage SDK using `encodeURIComponent` instead of `encodeURI` for the blob name.
This change ensures that Asset paths use `encodeURI` for the blob name:
```json
{ "url": "https://account.blob.core.windows.net/container/folder/file.pdf" }
```
> Do not uses slashes in blob name

- package.json
- src/react/components/pages/homepage/homePage.scss
- src/react/components/pages/homepage/homePage.tsx
Add banner for FR Studio migration.
> Add banner for FR Studio migration.

- README.ja-jp.md
- README.md
- README.zh-cn.md
Update README for pointing to latest tool.
> Update README for pointing to latest tool.

- src/react/components/pages/homepage/homePage.scss
- src/react/components/pages/homepage/homePage.tsx
Update banner message and style.  Attach screenshot.
> Update v2.0 API deprecation date
